# Generated by Django 3.1.2 on 2020-10-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-name',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
